[package]
name = "dify"
version = "0.2.0-alpha.2"
authors = ["jihchi <achi@987.tw>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.11"
getopts = "0.2"
anyhow = "1.0"
colored = "2.0.0"
