[package]
name = "dify"
version = "0.2.0-alpha.10"
authors = ["jihchi <achi@987.tw>"]
edition = "2018"
publish = false

[package.metadata.release]
pre-release-commit-message = "Bump version to {{version}}"

[dependencies]
image = "0.23.11"
getopts = "0.2"
anyhow = "1.0"
colored = "2.0.0"

